### ISSUE TITLE
application.conf and production.conf can be merged

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#438]
The current situation is overly complicated, instead of having a secret application.conf (which was like this in the old RoR app), we can simply override values with environment variables like:

```json
db.default {
  host = "localhost"
  host = ${?DB_HOST}
  database = "database_name"
  database = ${?DB_DATABASE}
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://"${db.default.host}":5432/"${db.default.database}"?reWriteBatchedInserts=true"
  url = ${?DATABASE_URL}
}
```

**Comment by felixgabler** [comment]
I agree that the current situation is overly complicated. However, I don't think that environment variables are much different from having another properties file.
In the Vue branch I include a file called application-ext.properties at the bottom of application.properties. The configuration in this file would override any configuration in application.properties.
I like this approach a lot because we can override values by just having another file in the conf folder.
(Note: All its properties should be defined in application.properties albeit empty if necessary)
WDYT?

**Comment by felixgabler** [comment]
If we get docker running, the paths in application.conf would be written according to the docker containers environment. Any secrets should be set via an .env file at that point, I guess. This would eliminate the need for extending the conf file
