### ISSUE TITLE
MODELLER parentid is always set to FALSE

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#629]
The value of parentid in the modeller script is always set to FALSE presently. If the input for MODELLER is forwarded by hhpred_manual, the PDB cif files created by hhpred_manual job should be used. This used to work several months ago, but I did not test this in a long time. This is a critical bug as worng files are used for modeling. 

https://github.com/proteinevolution/Toolkit/blob/573ff0c8279ced36085167d0713659ff94567ca7/tel/runscripts/modeller.sh#L31

The same logic is used when a job is forwarded from HHpred to hhpred_manual. The parentid is set correctly there though.

**Comment by zy4** [comment]
there should be only business logic if possible in the scala code, otherwise, I lose the overseight.
let's put this up as a todo, to avoid business logic in runscripts which should only be as declarative as docker scripts or YML config files.

I will also (while writing tests for it) and implement an instance (supposedly in `tel`) which validates all runscripts so that modification cannot break anything.

**Comment by vikramalva** [comment]
@zy4 Are you already working on this? If you have not started yet, please don't for now. I have a different idea of tackling this.

**Comment by zy4** [comment]
No. Only reasoned about but do share your ideas
