### ISSUE TITLE
Backend: Rewrite routes to match expected

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#676]
The backend will only be used as an API. THerefore we need to gradually get rid of all the twirl templates and change the routes to serve JSON as expected by the new frontend.

**Comment by zy4** [comment]
It would be nice to tackle #606 first in order to get rid of the mixed stack we have at the moment.
Circe seems to be more performant, popular and powerful compared to play-json. I already started to migrate ALL json generating and parsing code to circe and try to finish it this week before anyone else moves on with this issue.

This would also fix the fact that our main result models are still messy (#416 ).

As for this task: 
The most important aspect here is really that the result models are a mess. Once this is done, the rest should be quite repetitive.

**Comment by lukaszimmermann** [comment]
Does that now imply that I am not going to work on that issue for now?

**Comment by felixgabler** [comment]
https://github.com/timt/sbt-npm

Why not just use this?

**Comment by zy4** [comment]
Try it out :)

**Comment by felixgabler** [comment]
I ended up choosing a different path.
Yarn is now registered as a [PlayRunHook](https://www.playframework.com/documentation/2.6.x/SBTCookbook). WDYT?
I cannot fully test it from home because the toolkit won't launch correctly on windows ATM and the docker branch is not yet fully functioning.
Would be nice if someone could take a look.

What we still need to figure out is how to pass the correct port to the frontend so it can talk to the api.

**Comment by felixgabler** [comment]
Since this is not really a task and should rather be implemented gradually in other tasks, I am going to close this.
