### ISSUE TITLE
Database Logic should be restricted to the DAOs

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#824]
all selectors and modifiers should be contained within the dao methods and not being passed as `BSONDocuments`.

**Comment by felixgabler** [comment]
I already started this in the Auth ticket.

Remaining:
- [ ] UserDao.findUsers()
- [ ] UserDao.modifyUsers()
- [ ] BackendDao.modifyStats()
- [ ] JobDao.findJobs()
- [ ] JobDao.modifyJob()
- [ ] JobDao.countJobs()

**Comment by felixgabler** [comment]
In order to encapsulate the db logic for users inside the UserDAO, we would need to refactor the caching as well like I already did on the vue branch. Because this is a lot of unnecessary, duplicate work, I will close this ticket for now and wait until vue is done.
However, if anyone wants to do it anyways, please feel free to open the ticket again.
