### ISSUE TITLE
Master branch: Cluster workload is broken

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#830]
The load is only shown for a couple of minutes after the server is started.

**Comment by zy4** [comment]
going to finally fix this by reimplementing all actors

**Comment by zy4** [comment]
try again? /cc @vikramalva  (I want to get rid of qStat in the next step)

**Comment by zy4** [comment]
... in the develop branch of course

**Comment by vikramalva** [comment]
Appears to work normally; I am going to release a new version later this noon and check this on production.

**Comment by vikramalva** [comment]
Appears to also work normally on production.

**Comment by zy4** [comment]
Yeah, the reason was most likely that too many actor references were stored in order to message the load. Now we subscribe to the akka event bus which is more the standard way of broadcasting messages.

But still: It is absolutely unnecessary to execute qstat all the time. Our system knows how many jobs are running, we don't have to look it up. What could be improved IMHO is to calculate as follows:

count the number of secods which the oldest job is still in a queue times a factor which comes from the assigned ressources. I will implement a queue which does this soon.
