### ISSUE TITLE
backport action composition code into develop

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#905]
should be merged into develop before the vue code gets merged.
reasons: test separately, easier to review.

**Comment by felixgabler** [comment]
I don't think that the amount of work is worth doing this. In the end, the vue branch will become the new develop branch after some very thorough testing. This comprehensive testing has to take place anyway.

**Comment by zy4** [comment]
Is it that much work? I don't see the vue branch being merged any time soon but new controller methods being implemented in the meantime.

**Comment by felixgabler** [comment]
I would much rather spend the time on getting the vue branch done. In fact, I don't see much of a point in implementing new controller methods outside of the vue branch because they will have to be reimplemented for Vue anyways. I definitely don't have the time to spend twice the time for each feature.
Currently the toolkit runs fine and, except for hotfixes, all the effort is being rightly poured into Vue.

**Comment by zy4** [comment]
well, there is some WIP on my part which aims to trash the `JobActor`, including new controller methods.
