### ISSUE TITLE
Implement "graceful shutdown"

### ISSUE THREAD

**Issue by anjestephens** [proteinevolution/Toolkit#91]
We get quite a few error messages on shutdown (the mongodb collections and every connected websocket will throw one, for example)

**Comment by felixgabler** [comment]
With the new frontend we can easily implement this. There should also be a browser notification on maintenance alert.

**Comment by felixgabler** [comment]
I implemented most of the backend functionality for this. @vikramalva we have to talk some more about where to store the maintenance state. Right now, I store it in the controller directly. This way, after a restart, the maintenance mode warning would go away and it also doesn't need the database. Otherwise, one would have to manually remove the maintenance mode after finishing maintenance.

ToDo (@joeldomke):
- [ ] Implement admin view to trigger the POST routes /api/backend/startmaintenance and /api/backend/endmaintenance (use BackendService for this)
- [ ] Disable Submit buttons when in maintenance mode

**Comment by felixgabler** [comment]
We will postpone the admin view. Maintenance mode will be managed by calling the routes.
Do we want a browser notification?
