### ISSUE TITLE
Vue: Macmode and alignment mode interdependent on each other

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#918]
See [ParamAccess](https://github.com/proteinevolution/Toolkit/blob/vue/modules/params/src/main/scala/de/proteinevolution/params/ParamAccess.scala#L73).
We already talked about it some time ago.
It is implemented for hhpred in the production toolkit https://toolkit.tuebingen.mpg.de/#/tools/hhpred under Parameters

**Comment by sesati** [comment]
See [commit](https://github.com/proteinevolution/Toolkit/commit/f7fbd10c4d43b8e1882db34037eaff95f39c7362): This would be my approach to fixing this.

The problem is that I cannot test this at the moment since I always get an Error on submitting a job for HHpred. I pushed it to a separate branch for now.

**Comment by felixgabler** [comment]
Looks good to me. @vikramalva probably needs to change the wording a bit.
We also need to pull the translations into the frontend at some point.

**Comment by vikramalva** [comment]
@felixgabler @sesati don't merge this to the vue branch yet.
