### ISSUE TITLE
Vue: ParamValues are not being displayed on submit

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#931]
When one submits a job, the ParamValues are not displayed immediately. The values will appear after reloading the tool view.
This happens because the "text" property in TextAreaSubComponent ist only set on component creation.
The question is also why they disappear on submission.

**Comment by sesati** [comment]
The problem was that the "text" property didn't react to changes to the "value" prop. The job details need some time to be fetched (this happens after submission) - the "value" prop therefore only contains the correct alignment value after some time, and it is empty beforehand.

I fixed it by getting rid of the "text" property entirely and directly binding the value prop to the text area, and emitting any changes via events. I think it is more elegant to not have this intermediate data field this way, and it seems to work fine.
